//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gelengidentablosu
{
    using System;
    using System.Collections.Generic;
    
    public partial class kartlar
    {
        public int kartid { get; set; }
        public string kartad { get; set; }
        public string alınan { get; set; }
        public Nullable<int> fiyat { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
