//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gelengidentablosu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class giderdatabaseEntities3 : DbContext
    {
        public giderdatabaseEntities3()
            : base("name=giderdatabaseEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<gelenler> gelenler { get; set; }
        public virtual DbSet<gidenler> gidenler { get; set; }
        public virtual DbSet<kartlar> kartlar { get; set; }
    }
}
